### ISSUE TITLE
Error in conversion

### ISSUE THREAD

**Issue by saswat0** [yan-wyb/models-zoo#1]
I tried to convert a resnet50 model using ksnn convert script and ran into the following error

```
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value resnet_v1_50/block3/unit_3/bottleneck_v1/conv3/BatchNorm/moving_mean 

[[{{node _retval_resnet_v1_50/block3/unit_3/bottleneck_v1/conv3/BatchNorm/moving_mean_0_40}}]]
```
I've downloaded the pb file using tf_slim's export_inference_graph.py code

However, converting inception_v3.pb file runs without any errors. Is this an environment issue (if yes, please attach the exact versions for the packages) or does it have to do something with the way the models are trained?

Steps to reproduce:

- Download the resnet50 pb file using [tf_slim](https://github.com/tensorflow/models/tree/master/research/slim)
```
python export_inference_graph.py \
  --alsologtostderr \
  --model_name=resnet_v1_50 \
  --output_file=./resnet_v1_graph.pb
```
- Run the conversion [script](https://github.com/khadas/aml_npu_sdk)
```./convert --model-name resnet_v1_50 \
--platform tensorflow \
--model ~/models/research/slim/resnet_v2_graph.pb \
--input-size-list '224,224,3' \
--inputs input \
--outputs resnet_v1_50/predictions/Reshape_1 \
--mean-values '128 128 128 128' \
--quantized-dtype asymmetric_affine \
--kboard VIM3 --print-level 1
```

Full error trace:
```
2021-11-30 05:47:22.541820: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA

2021-11-30 05:47:22.546108: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2000129999 Hz

2021-11-30 05:47:22.546329: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5cef110 executing computations on platform Host. Devices:

2021-11-30 05:47:22.546354: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version

[18393] Failed to execute script pegasus

Traceback (most recent call last):

  File "tensorflow_core/python/client/session.py", line 1365, in _do_call

  File "tensorflow_core/python/client/session.py", line 1350, in _run_fn

  File "tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun

tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value resnet_v1_50/block3/unit_3/bottleneck_v1/conv3/BatchNorm/moving_mean

         [[{{node _retval_resnet_v1_50/block3/unit_3/bottleneck_v1/conv3/BatchNorm/moving_mean_0_40}}]]



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "pegasus.py", line 131, in <module>

  File "pegasus.py", line 112, in main

  File "acuitylib/app/importer/commands.py", line 205, in execute

  File "acuitylib/vsi_nn.py", line 49, in load_tensorflow

  File "acuitylib/app/importer/import_tensorflow.py", line 102, in run

  File "acuitylib/converter/convert_tf.py", line 606, in pre_process

  File "acuitylib/converter/tensorflowloader.py", line 103, in pre_proces

  File "acuitylib/converter/tensorflowloader.py", line 856, in calc_2_const

  File "acuitylib/converter/tf_util.py", line 409, in query_tensor

  File "tensorflow_core/python/client/session.py", line 956, in run

  File "tensorflow_core/python/client/session.py", line 1180, in _run

  File "tensorflow_core/python/client/session.py", line 1359, in _do_run

  File "tensorflow_core/python/client/session.py", line 1384, in _do_call

tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value resnet_v1_50/block3/unit_3/bottleneck_v1/conv3/BatchNorm/moving_mean

         [[{{node _retval_resnet_v1_50/block3/unit_3/bottleneck_v1/conv3/BatchNorm/moving_mean_0_40}}]]
```

**Comment by saswat0** [comment]
Fixed it. Apparently the model needed to be frozen using tensorflow's freeze_graph method and then converted
